name: Quality Assurance

on:
  pull_request:
    branches: [main]

jobs:
  lint-and-unit-tests:
    name: Lint and unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        id: deps
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test (unit)
        if: ${{ steps.deps.conclusion == 'success' }}
        run: npm run test:unit
  integration-tests:
    name: Integration tests
    strategy:
      matrix:
        version: [ 16 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run integration tests
        run: npm run test:e2e:ci
